# Generated by Django 3.2.9 on 2021-12-20 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_image',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.ImageField(blank=True, default=False, upload_to='photos/products'),
        ),
    ]
