# Generated by Django 3.2.9 on 2021-12-21 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_variation'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='variation',
            table='Variation',
        ),
    ]
